// Generated by SAP AFX Compiler (Tue Mar 10 11:04:35 CET 2015)

#ifndef SAP_XS_ATOM_H
#define SAP_XS_ATOM_H

#include "sap_xs_runtime.h"

@class XS_AtomException;
@class XS_AtomLink;
@class XS_AtomValue;
@class XS_AtomDeltaStream;
@class XS_GeoATOM;

@interface XS_AtomException : NSException
{
    @protected NSString* message_;
}
/* public */ @property (readonly, strong) NSString* message;
/* private */ - (id) init;
/* public */ - (NSString*) message;
+ (XS_AtomException*) new;
/* private */ - (void) privateInit;
/* public */ + (XS_AtomException*) withMessage :(NSString*)param_message;
/* private */ + (XS_AtomException*) DC1 :(NSString*)p1;
@end

/* internal */ @interface XS_AtomLink : NSObject
{
    @private xs_int type_;
    @private NSString* url_;
}
/* public */ @property xs_int type;
/* public */ @property (strong) NSString* url;
/* private */ - (id) init;
/* public */ + (XS_AtomLink*) new;
/* public */ - (xs_int) type;
/* public */ - (void) setType :(xs_int)value;
/* public */ - (NSString*) url;
/* public */ - (void) setUrl :(NSString*)value;
@end

#define XS_AtomLink_DELTA_LINK 1
#define XS_AtomLink_NEXT_LINK 2
#define XS_AtomLink_READ_LINK 3

@interface XS_AtomValue : NSObject
/* public */ + (void) fromValue :(XS_XmlElement*)element :(XS_DataValue*)value :(XS_DataContext*)context;
/* public */ + (void) fromValueList :(XS_XmlElement*)element :(XS_DataValueList*)list :(XS_DataContext*)context;
/* public */ + (void) fromComplex :(XS_XmlElement*)element :(XS_ComplexValue*)value :(XS_DataContext*)context;
/* public */ + (void) fromComplexList :(XS_XmlElement*)element :(XS_ComplexValueList*)list :(XS_DataContext*)context;
/* public */ + (void) fromEntity :(XS_XmlElement*)entry :(XS_EntityValue*)entity :(XS_DataContext*)context;
/* public */ + (XS_DataValue*) getValue :(XS_XmlElement*)element :(XS_DataType*)type :(XS_DataContext*)context;
/* public */ + (XS_DataValueList*) getValueList :(XS_XmlElement*)element :(XS_DataType*)type :(XS_DataContext*)context;
/* public */ + (XS_ComplexValue*) getComplex :(XS_XmlElement*)element :(XS_ComplexType*)type :(XS_DataContext*)context;
/* public */ + (XS_ComplexValueList*) getComplexList :(XS_XmlElement*)element :(XS_DataType*)type :(XS_DataContext*)context;
/* public */ + (XS_EntityValue*) getEntity :(XS_XmlElement*)entry :(XS_EntityType*)type :(XS_DataContext*)context;
/* public */ + (XS_EntityValueList*) getEntityList :(XS_XmlElement*)feed :(XS_DataType*)type :(XS_DataContext*)context;
/* public */ + (XS_DataValue*) parseDocument :(XS_XmlElement*)element :(XS_DataType*)type :(XS_DataContext*)context;
/* public */ + (XS_DeferredValue*) parseLink :(XS_XmlElement*)element :(XS_EntityType*)type :(XS_DataContext*)context;
/* public */ + (XS_ObjectList*) parseLinks :(XS_XmlElement*)element :(XS_EntityType*)type :(XS_DataContext*)context;
/* public */ + (XS_XmlDocument*) formatLink :(XS_EntityValue*)entity :(XS_DataContext*)context;
/* public */ + (XS_XmlDocument*) formatCall :(XS_MethodCall*)call :(XS_DataContext*)context;
/* public */ + (XS_ErrorResponse*) errorResponse :(XS_XmlElement*)element :(XS_DataContext*)context;
/* public */ + (XS_XmlDocument*) entryDocument :(XS_EntityValue*)entity :(XS_DataContext*)context;
/* private */ + (void) deepInsert :(XS_XmlElement*)entry :(XS_PropertyInfo*)pi :(XS_DataValue*)dv :(XS_DataContext*)context :(XS_EntityValue*)parent;
/* private */ + (XS_XmlElement*) rootElement :(NSString*)name :(XS_DataContext*)context;
/* private */ + (xs_boolean) isNull :(XS_XmlElement*)element;
/* private */ + (void) setNull :(XS_XmlElement*)element;
/* private */ + (NSString*) odataName :(XS_DataType*)type :(XS_DataContext*)context;
/* private */ + (NSString*) actualTypeName :(XS_XmlElement*)element :(NSString*)attName :(XS_DataContext*)context;
/* private */ + (XS_ComplexType*) actualComplexType :(XS_XmlElement*)element :(XS_ComplexType*)formalType :(XS_DataContext*)context;
/* private */ + (XS_EntityType*) actualEntityType :(XS_XmlElement*)category :(XS_EntityType*)formalType :(XS_DataContext*)context;
/* private */ + (XS_DataType*) resolveOpenType :(NSString*)type :(XS_DataContext*)context;
/* private */ + (XS_LocalDateTime*) parseLocalDT :(NSString*)s;
/* private */ + (XS_StreamLink*) DC1 :(NSString*)p1;
/* private */ + (XS_XmlDocument*) DC2 :(XS_XmlElement*)p1;
@end

#define XS_AtomValue_ATOM_ENTRY @"application/atom+xml;type=entry"
#define XS_AtomValue_ATOM_FEED @"application/atom+xml;type=feed"
#define XS_AtomValue_AUTHOR @"author"
#define XS_AtomValue_CONTENT @"content"
#define XS_AtomValue_CONTEXT @"context"
#define XS_AtomValue_COUNT @"count"
#define XS_AtomValue_EDIT @"edit"
#define XS_AtomValue_ENTRY @"entry"
#define XS_AtomValue_DELETED_ENTRY @"deleted-entry"
#define XS_AtomValue_DELETED_LINK @"deleted-link"
#define XS_AtomValue_DELTA @"delta"
#define XS_AtomValue_FEED @"feed"
#define XS_AtomValue_HREF @"href"
#define XS_AtomValue_ID @"id"
#define XS_AtomValue_M_CONTEXT @"m:context"
#define XS_AtomValue_M_ELEMENT @"m:element"
#define XS_AtomValue_M_INLINE @"m:inline"
#define XS_AtomValue_M_NULL @"m:null"
#define XS_AtomValue_M_TYPE @"m:type"
#define XS_AtomValue_NS_DELTA @"http://docs.oasis-open.org/odata/ns/delta"
#define XS_AtomValue_LINK @"link"
#define XS_AtomValue_NAME @"name"
#define XS_AtomValue_NEXT @"next"
#define XS_AtomValue_REASON @"reason"
#define XS_AtomValue_PROPERTIES @"properties"
#define XS_AtomValue_REF @"ref"
#define XS_AtomValue_REL @"rel"
#define XS_AtomValue_RELATIONSHIP @"relationship"
#define XS_AtomValue_SCHEME @"scheme"
#define XS_AtomValue_SOURCE @"source"
#define XS_AtomValue_SELF @"self"
#define XS_AtomValue_SRC @"src"
#define XS_AtomValue_SUMMARY @"summary"
#define XS_AtomValue_TARGET @"target"
#define XS_AtomValue_TERM @"term"
#define XS_AtomValue_TITLE @"title"
#define XS_AtomValue_TYPE @"type"
#define XS_AtomValue_UPDATED @"updated"
#define XS_AtomValue_V3_EDIT_MEDIA @"http://schemas.microsoft.com/ado/2007/08/dataservices/edit-media/"
#define XS_AtomValue_V3_RELATED @"http://schemas.microsoft.com/ado/2007/08/dataservices/related/"
#define XS_AtomValue_V3_SCHEME @"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"
#define XS_AtomValue_V4_EDIT_MEDIA @"http://docs.oasis-open.org/odata/ns/edit-media/"
#define XS_AtomValue_V4_RELATED @"http://docs.oasis-open.org/odata/ns/related/"
#define XS_AtomValue_V4_SCHEME @"http://docs.oasis-open.org/odata/ns/scheme"

@interface XS_AtomDeltaStream : XS_DeltaStream
{
    @private XS_DataContext* dataContext;
    @private XS_CharStream* charStream;
    @private XS_XmlParser* atomStream;
    @private xs_boolean endElement;
    @private xs_boolean firstItem;
}
/* private */ - (id) init;
+ (XS_AtomDeltaStream*) new;
/* private */ - (void) privateInit;
/* public */ + (XS_AtomDeltaStream*) fromStream :(XS_CharStream*)stream :(XS_DataContext*)context;
/* public */ - (void) abort;
/* public */ - (void) close;
/* public */ - (xs_boolean) next;
/* public */ + (id) parseItem :(XS_XmlElement*)item :(XS_DataContext*)context;
/* private */ + (XS_AtomDeltaStream*) DC1 :(XS_XmlParser*)p1 :(XS_CharStream*)p2 :(XS_DataContext*)p3 :(xs_boolean)p4;
/* private */ + (XS_AtomLink*) DC2 :(xs_int)p1 :(NSString*)p2;
@end

@interface XS_GeoATOM : NSObject
/* public */ + (XS_DataValue*) parse :(XS_XmlElement*)geo :(XS_DataType*)type;
/* public */ + (void) format :(XS_XmlElement*)geo :(XS_DataValue*)value;
/* private */ + (XS_GeographyValue*) parseGeography :(XS_XmlElement*)geo :(xs_int)tc :(XS_GeographyValue*)gv;
/* private */ + (XS_GeometryValue*) parseGeometry :(XS_XmlElement*)geo :(xs_int)tc :(XS_GeometryValue*)gv;
/* private */ + (void) parseSRS :(XS_XmlElement*)element :(XS_DataValue*)dv;
/* private */ + (XS_PointCoordinates*) parsePoint :(XS_XmlElement*)geo :(XS_DataValue*)dv;
/* private */ + (XS_MultiPointCoordinates*) parseMultiPoint :(XS_XmlElement*)geo :(XS_DataValue*)dv;
/* private */ + (XS_CurveCoordinates*) parseLineString :(XS_XmlElement*)geo :(XS_DataValue*)dv;
/* private */ + (XS_MultiCurveCoordinates*) parseMultiLineString :(XS_XmlElement*)geo :(XS_DataValue*)dv;
/* private */ + (XS_PolygonCoordinates*) parsePolygon :(XS_XmlElement*)geo :(XS_DataValue*)dv;
/* private */ + (XS_MultiPolygonCoordinates*) parseMultiPolygon :(XS_XmlElement*)geo :(XS_DataValue*)dv;
/* private */ + (XS_GeographyValueList*) parseGeographyValueList :(XS_XmlElement*)geo;
/* private */ + (XS_GeometryValueList*) parseGeometryValueList :(XS_XmlElement*)geo;
/* private */ + (NSString*) formatSRS :(xs_int)srsCode :(NSString*)srsName;
/* private */ + (XS_XmlElement*) formatPos :(XS_PointCoordinates*)pc :(xs_int)srsCode;
/* private */ + (NSString*) formatPosText :(XS_PointCoordinates*)pc :(xs_int)srsCode;
/* private */ + (XS_XmlElement*) formatPosList :(XS_MultiPointCoordinates*)mpc :(xs_int)srsCode;
/* private */ + (XS_XmlElement*) formatCurve :(XS_CurveCoordinates*)curve :(xs_int)srsCode;
/* private */ + (void) formatPoint :(XS_XmlElement*)geo :(XS_PointCoordinates*)value :(xs_int)srsCode :(NSString*)srsName :(xs_boolean)isNested;
/* private */ + (void) formatMultiPoint :(XS_XmlElement*)geo :(XS_MultiPointCoordinates*)value :(xs_int)srsCode :(NSString*)srsName :(xs_boolean)isNested;
/* private */ + (void) formatLineString :(XS_XmlElement*)geo :(XS_CurveCoordinates*)value :(xs_int)srsCode :(NSString*)srsName :(xs_boolean)isNested;
/* private */ + (void) formatMultiLineString :(XS_XmlElement*)geo :(XS_MultiCurveCoordinates*)value :(xs_int)srsCode :(NSString*)srsName :(xs_boolean)isNested;
/* private */ + (void) formatPolygon :(XS_XmlElement*)geo :(XS_PolygonCoordinates*)value :(xs_int)srsCode :(NSString*)srsName :(xs_boolean)isNested;
/* private */ + (void) formatMultiPolygon :(XS_XmlElement*)geo :(XS_MultiPolygonCoordinates*)value :(xs_int)srsCode :(NSString*)srsName :(xs_boolean)isNested;
/* private */ + (void) formatMultiGeography :(XS_XmlElement*)geo :(XS_GeographyValueList*)value;
/* private */ + (void) formatMultiGeometry :(XS_XmlElement*)geo :(XS_GeometryValueList*)value;
/* private */ + (XS_AtomException*) cannotParse :(XS_XmlElement*)element;
/* private */ + (void) findAll :(XS_XmlElement*)element :(NSString*)name :(XS_XmlElementList*)list;
/* private */ + (XS_XmlElement*) findOne :(XS_XmlElement*)element :(NSString*)name;
/* private */ + (XS_StringList*) parseList :(NSString*)text;
/* private */ + (XS_StringList*) trimList :(XS_StringList*)list;
@end

#define XS_GeoATOM_COORDINATES @"coordinates"
#define XS_GeoATOM_EXTERIOR @"exterior"
#define XS_GeoATOM_LINE_STRING @"LineString"
#define XS_GeoATOM_LINEAR_RING @"LinearRing"
#define XS_GeoATOM_MULTI_LINE_STRING @"MultiLineString"
#define XS_GeoATOM_MULTI_CURVE @"MultiCurve"
#define XS_GeoATOM_MULTI_POINT @"MultiPoint"
#define XS_GeoATOM_MULTI_POLYGON @"MultiPolygon"
#define XS_GeoATOM_MULTI_SURFACE @"MultiSurface"
#define XS_GeoATOM_POINT @"Point"
#define XS_GeoATOM_POLYGON @"Polygon"
#define XS_GeoATOM_POS @"pos"
#define XS_GeoATOM_POS_LIST @"posList"
#define XS_GeoATOM_SRS_NAME @"srsName"

#endif
