// Generated by SAP AFX Compiler (Tue Mar 10 11:04:42 CET 2015)

#ifndef SAP_XS_DATA2_H
#define SAP_XS_DATA2_H

#include "sap_xs_runtime.h"

@class XS_DataPart2;

/* internal */ @interface XS_DataPart2 : NSObject
@end

#endif
